// src/pages/admin/AdminDashboard.jsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../../utils/api';
import { useAuth } from '../../hooks/useAuth';

export default function AdminDashboard() {
  const [stats, setStats] = useState(null);
  const [logs,  setLogs]  = useState([]);
  const { user } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    api.get('/stats').then((r) => setStats(r.data.data)).catch(() => {});
    api.get('/timetable/logs').then((r) => setLogs(r.data.data.slice(0, 5))).catch(() => {});
  }, []);

  const statItems = stats ? [
    { icon: '👤', label: 'Teachers',   value: stats.teachers,         color: 'var(--accent)' },
    { icon: '📘', label: 'Subjects',   value: stats.subjects,         color: 'var(--teal)' },
    { icon: '🏛', label: 'Rooms',      value: stats.rooms,            color: 'var(--amber)' },
    { icon: '🎓', label: 'Sections',   value: stats.sections,         color: 'var(--green)' },
    { icon: '⊞',  label: 'TT Entries', value: stats.timetableEntries, color: 'var(--accent)' },
  ] : [];

  const quickActions = [
    { label: '⚡ Generate Timetable', path: '/admin/generate',   style: 'btn-primary' },
    { label: '⊞ View Timetable',     path: '/admin/timetable',  style: 'btn-secondary' },
    { label: '📋 Manage Curriculum', path: '/admin/curriculum', style: 'btn-secondary' },
    { label: '⚠ Conflict Logs',     path: '/admin/conflicts',  style: 'btn-secondary' },
  ];

  return (
    <div className="fade-in-up">
      <div className="page-header">
        <div>
          <h1>Dashboard</h1>
          <p>Welcome back, {user?.username}. Here's your system overview.</p>
        </div>
      </div>

      {/* Stats */}
      <div className="stats-grid">
        {statItems.map((s) => (
          <div key={s.label} className="stat-card" style={{ '--accent': s.color }}>
            <span className="stat-icon">{s.icon}</span>
            <div className="stat-value">{s.value}</div>
            <div className="stat-label">{s.label}</div>
          </div>
        ))}
      </div>

      {/* Quick actions */}
      <div className="card" style={{ marginBottom: 20 }}>
        <h3 style={{ marginBottom: 14, fontFamily: 'var(--font-display)', fontSize: '1rem' }}>Quick Actions</h3>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          {quickActions.map((a) => (
            <button key={a.path} className={`btn ${a.style}`} onClick={() => navigate(a.path)}>
              {a.label}
            </button>
          ))}
        </div>
      </div>

      {/* Recent generation logs */}
      <div className="card">
        <h3 style={{ marginBottom: 14, fontFamily: 'var(--font-display)', fontSize: '1rem' }}>
          Recent Timetable Generations
        </h3>
        {logs.length === 0 ? (
          <p className="text-muted text-sm">No generations yet. Use ⚡ Generate Timetable to get started.</p>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Log ID</th>
                <th>Generated By</th>
                <th>Algorithm</th>
                <th>Entries</th>
                <th>Conflicts</th>
                <th>Status</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              {logs.map((log) => (
                <tr key={log.log_id}>
                  <td><span className="badge badge-blue">#{log.log_id}</span></td>
                  <td>{log.generated_by_username || '—'}</td>
                  <td><code style={{ fontSize: '0.75rem', color: 'var(--teal)' }}>{log.algorithm}</code></td>
                  <td><strong>{log.entries_created}</strong></td>
                  <td>
                    {log.conflicts_found > 0
                      ? <span className="badge badge-amber">{log.conflicts_found}</span>
                      : <span className="badge badge-green">0</span>}
                  </td>
                  <td>
                    <span className={`badge badge-${log.status === 'success' ? 'green' : log.status === 'partial' ? 'amber' : 'red'}`}>
                      {log.status}
                    </span>
                  </td>
                  <td className="text-muted text-sm">{new Date(log.generated_at).toLocaleString()}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
